/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRoleRequirementsRouteImport } from './routes/_app.role-requirements'
import { Route as AppOperatorsRouteImport } from './routes/_app.operators'
import { Route as AppManageRouteImport } from './routes/_app.manage'
import { Route as AppLogRouteImport } from './routes/_app.log'
import { Route as AppCompetencesRouteImport } from './routes/_app.competences'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleRequirementsRoute = AppRoleRequirementsRouteImport.update({
  id: '/role-requirements',
  path: '/role-requirements',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorsRoute = AppOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetencesRoute = AppCompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/competences': typeof AppCompetencesRoute
  '/log': typeof AppLogRoute
  '/manage': typeof AppManageRoute
  '/operators': typeof AppOperatorsRoute
  '/role-requirements': typeof AppRoleRequirementsRoute
}
export interface FileRoutesByTo {
  '/competences': typeof AppCompetencesRoute
  '/log': typeof AppLogRoute
  '/manage': typeof AppManageRoute
  '/operators': typeof AppOperatorsRoute
  '/role-requirements': typeof AppRoleRequirementsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/competences': typeof AppCompetencesRoute
  '/_app/log': typeof AppLogRoute
  '/_app/manage': typeof AppManageRoute
  '/_app/operators': typeof AppOperatorsRoute
  '/_app/role-requirements': typeof AppRoleRequirementsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competences'
    | '/log'
    | '/manage'
    | '/operators'
    | '/role-requirements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/competences'
    | '/log'
    | '/manage'
    | '/operators'
    | '/role-requirements'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/competences'
    | '/_app/log'
    | '/_app/manage'
    | '/_app/operators'
    | '/_app/role-requirements'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/role-requirements': {
      id: '/_app/role-requirements'
      path: '/role-requirements'
      fullPath: '/role-requirements'
      preLoaderRoute: typeof AppRoleRequirementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operators': {
      id: '/_app/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AppOperatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage': {
      id: '/_app/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log': {
      id: '/_app/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competences': {
      id: '/_app/competences'
      path: '/competences'
      fullPath: '/competences'
      preLoaderRoute: typeof AppCompetencesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompetencesRoute: typeof AppCompetencesRoute
  AppLogRoute: typeof AppLogRoute
  AppManageRoute: typeof AppManageRoute
  AppOperatorsRoute: typeof AppOperatorsRoute
  AppRoleRequirementsRoute: typeof AppRoleRequirementsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompetencesRoute: AppCompetencesRoute,
  AppLogRoute: AppLogRoute,
  AppManageRoute: AppManageRoute,
  AppOperatorsRoute: AppOperatorsRoute,
  AppRoleRequirementsRoute: AppRoleRequirementsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
